dist: xenial
sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get update
  - sudo apt-get install -y texlive texlive-base texlive-latex-extra texlive-fonts-extra
    python-virtualenv librsvg2-bin
  - wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-linux.tar.gz
  - tar -xzvf pandoc-2.5-linux.tar.gz
  - rm pandoc-2.5-linux.tar.gz
  - sudo mv pandoc-2.5 /opt
  - sudo chmod +x /opt/pandoc-2.5/bin/pandoc
  - sudo ln -s /opt/pandoc-2.5/bin/pandoc /usr/local/bin/pandoc
  - sudo ln -s /opt/pandoc-2.5/bin/pandoc-citeproc /usr/local/bin/pandoc-citeproc
script:
  - cd spec-publisher
  - mvn clean package
  - java -jar target/mets-profile-proc.jar ../profile/E-ARK-CSIP.xml
  - cd ..
  - bash create-site.sh
  - bundle install
  - bundle exec jekyll build -s ./docs -d ./_site
  - bundle exec htmlproofer ./_site --file-ignore /javadoc/ --only-4xx --check-html
  - cd spec-publisher
  - git checkout feat/pdf-publication
  - mvn clean package
  - java -jar target/mets-profile-proc.jar ../profile/E-ARK-CSIP.xml
  - cd ..
  - bash create-pdf.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  local_dir: docs
  fqdn: earkcsip.dilcis.eu
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: hI697DAe+XfkG4Ouf0HnU4lkysBZMSzwRJJPKLR46fG5VaLcwvpKO0WCavHB8EK2WWJh4zVPQVmt/Sc/dQRoG/bBIOxl8RRoxZxynqr9DSoeJzJY7NaapmovfH3mr8kSMGJiM6al/U0SpHCxUu2SLXKfPeuJKwynrwTDhCRr6QhI9mOJC1FMJl2cBgax5ScHGPxO/LiyeWCJpCfwoDWO6w5Qq689PwvwCnKJIgywG0zzBhD2Gxv3IN4j5Oi0KHFYns5bc7B0JtrPQjEBCtTMlrFnbKvB0dQQlIUCe+wSRVOpxvD4RtyRQBDhHmW9tNMpz148m1wL6TGTRvP5JYRyruIciloxlx9JBH3gm5C5xyVv7sUB4p8gO/h+zngugoQrMQckmrmC7bR5PMH9NLB7vGfSjYmpNb9JOPNbsih4kApt1k2WlJ2a3OjaRnyA2R34tBspChF+iwAwkjid58+1BnwZq0iLy6lPJqfPSqthq7Zz5xIHP5c/6u1X2wDrK69wxuphd/EFOVg1U1zh1tSSqgJIZAieoYwPLKQ+r4J2vVKEL87wZacruMD2uPCusHOp+fkKT/DTYH9k+UC24Q3sGkdWikZaBySIwUmZZ2bN07XWRXX7w1Miaqt5LH8TKinjBROySQFkgecqQQDJU9VM/8stGRrh5m+PMeXiFruMtrg=
  - secure: sfvnMA94DEvR+7qzNQ2Lb6CL3Ll5AFjK0GSHDVYRieiNtpC6gLWIoSiwORkoVWdePp41otBhE23UnWRh+rfZMVuWw7NRw3MBvTiMJErzZ/BNk9jw/BufgjxhePeqUaMDXeIMUw6rTjdzmJfCXx5qUojJwKVlUrRBh/KSGMN9VuVkm6uDn6GiScWZYsM9sW3L9aZHjz606nEd0yCkQaZanwrXkgJEfUWFpJd/bZcwv3AMW30dqFU2OcXdQ6SHGw2sFnPndxOSDzHgM2JfYD0hTPm01LpxibpsbgQBGRiLha9NyZrYXYA5sr+gy4eevpKJEvtv7KgxRbQ6EUQMapEXCxL1w/dKGEWJ4202fcoY2ezsTdfn4SkjHSSSOmISFyZl1qGh+keR8Gh3t8SrzKBmLivLS16ySJqGmZOBJk2BriaDS/rJWuai2rUIuKFXCxlJMaDQ96oV3M2Psp0SPWJSi8aECiBpEC0xOM7RG7Mu0aNdYAVvPO7U1HZCHZ5rRO1EL0sGODzX7+Uc21NDtyKCXdXzJqZkP4AjcB4Q2/n1KD4i0yo0ylHAwz5pBklX3nsHoXg/MUpm2VYAwU8nHTFBg7Zdyg2OwK6yKrNSy9Gqfse3rJ3qm8hlr+Pme1MCYQ7ew9NpsJ9wDl6tE/vWIJnJmMyIBrvIV5PZ1sWsbEhNzOc=
